### ISSUE TITLE
Sampling Rate Mismatch in preprocess_raw Causes Merge Error

### ISSUE THREAD

**Issue by nqdu** [noisepy/NoisePy#334]
Hi,

I'm trying to download data using the `download` module of noisepy. However, I occasionally encounter an error in function `preprocess_raw` with "Can't merge traces with same ids but differing sampling rates"

This error occurs at line 150 (see attached figure):

![Image](https://github.com/user-attachments/assets/f4625fed-fc2a-4aa7-8dd7-f8881ad4ef62).

Upon inspecting the sampling rates in the stream, I found a slight discrepancy—40 Hz vs. 40.000016 Hz—causing the merge failure. I also checked the `check_sample_gaps` function, which performs sanity checks on the sampling rate but only compares the integer part: 

![Image](https://github.com/user-attachments/assets/4e712b88-25b3-45cf-a84c-b187c03a0675)

I believe more refined sanity checks should be performed, such as:

1. comparing the real numbers instead of just their integer parts. 
2. resample data to force  all traces have exactly same sampling rate.

**Comment by niyiyu** [comment]
Hi @nqdu,

Thanks for pointing this out. Could you share with us what data you are downloading that you see the problem? It would be helpful if we can reproduce exceptions.

Thanks,
Yiyu

**Comment by nqdu** [comment]
> Hi [@nqdu](https://github.com/nqdu),
> 
> Thanks for pointing this out. Could you share with us what data you are downloading that you see the problem? It would be helpful if we can reproduce exceptions.
> 
> Thanks, Yiyu

Thanks Yiyu,

You can try this example with CLI: `noisepy download --config config.yml --raw_data_path ./tmpdata/RAW_DATA`
``` yaml
start_date: '2010-07-08T00:00:00Z'
end_date: '2010-07-09T00:00:00Z'
sampling_rate: 1
cc_len: 2000
lamin: 45
lamax: 46.5
lomin: -124
lomax: -123
step: 1000.0
freqmin: 0.01
freqmax: 0.4
freq_norm: rma
time_norm: rma
cc_method: xcorr
smooth_N: 10
smoothspect_N: 10
substack: true
substack_windows: 1
maxlag: 600
inc_hours: 12
max_over_std: 10
ncomp: 1
stationxml: false
rm_resp: inv
rm_resp_out: DISP
respdir: null
acorr_only: false
xcorr_only: true
stack_method: linear
keep_substack: false
rotation: true
correction: false
correction_csv: null
down_list: false
networks: ['TA']
stations: ['F04D']
channels: ["BHZ"]
client_url_key: 'iris'

```
